---
# FIXME: No ansible fact present for current timezone in a valid format.
- name: Fetch timezone facts
  shell: timedatectl status | grep "Time zone" | grep "{{ time_timezone }}"
  ignore_errors: yes
  register: timezone_status
  changed_when: timezone_status.rc != 0
  failed_when: timezone_status.rc != 1 and timezone_status.rc != 0
  tags:
    - config
    - time

- name: Set timezone
  command: timedatectl set-timezone "{{ time_timezone }}"
  when: timezone_status.rc == 1
  tags:
    - config
    - time
